[package]
name = "linkserver"
version = "0.1.0"
authors = ["bbangert@mozilla.com"]
license = "MPL-2.0"

[dependencies]
actix = "0.5"
actix-web = "0.6.14"
futures = "0.1"
rand = "0.5.2"
serde = "1.0.67"
serde_derive = "1.0.67"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
